src/ayama/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path, re_path

import accounts.urls
import clients.urls
import practises.urls
import profiles.urls
import calculator.urls

from . import views

# Personalized admin site settings like title and header
admin.site.site_title = "Ayama Site Admin"
admin.site.site_header = "Ayama Administration"

urlpatterns = [
    re_path(r"^healthz/", views.healthz, name="healthz"),
    path("", views.HomePage.as_view(), name="home"),
    path("about/", views.AboutPage.as_view(), name="about"),
    path("users/", include(profiles.urls)),
    path("admin/", admin.site.urls),
    path("", include(accounts.urls)),
    path("", include(practises.urls)),
    path("", include(clients.urls)),
    path("calcs/", include(calculator.urls)),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [path("__debug__/", include(debug_toolbar.urls))]

    # Dev ref for profile pics -- should probably redo this at some point
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/clients/urls.py
from django.urls import path

from .forms import (
    AddClientContactDetailForm,
    AddClientDependentDetailsForm,
    AddClientDetailForm,
    AddClientEmploymentDetailForm,
    AddClientNoteForm,
    AddClientProductsForm,
    AddClientRatesAndReturnForm,
)
from .views import (
    AddClientDependentView,
    AddClientNoteView,
    AdvisorClientsView,
    ClientlistView,
    ClientNoteListView,
    ClientSummaryView,
    ClientWizard,
    EditClientCommunicationFrequencyView,
    EditClientContactView,
    EditClientDependentView,
    EditClientDetailsView,
    EditClientEmploymentView,
    EditClientNoteView,
    EditClientRatesView,
    UpdateClientCommunicationHistoryView,
    UpdateLastSeen,
)

app_name = "clients"
urlpatterns = [
    path(
        "clients/",
        ClientWizard.as_view(
            [
                AddClientDetailForm,
                AddClientContactDetailForm,
                AddClientEmploymentDetailForm,
                AddClientRatesAndReturnForm,
                AddClientProductsForm,
            ]
        ),
        name="add-client",
    ),
    path(
        "add_client_dependents/",
        AddClientDependentView.as_view(),
        name="add-client-dependents",
    ),
    path("clients_list/", ClientlistView.as_view(), name="clients-list"),
    path("advisor_clients/", AdvisorClientsView.as_view(), name="advisor-clients"),
    path("client_summary/<pk>/", ClientSummaryView.as_view(), name="client-summary"),
    path(
        "edit_client/<pk>/", EditClientDetailsView.as_view(), name="edit-client-details"
    ),
    path(
        "edit_client_contact/<pk>/",
        EditClientContactView.as_view(),
        name="edit-client-contact",
    ),
    path("update_comms", UpdateLastSeen.as_view(), name="update-comms",),
    path(
        "edit_client_employment/<pk>/",
        EditClientEmploymentView.as_view(),
        name="edit-client-employment",
    ),
    path(
        "edit_client_rates/<pk>/",
        EditClientRatesView.as_view(),
        name="edit-client-rates",
    ),
    path(
        "edit_client_dependent/<pk>/",
        EditClientDependentView.as_view(),
        name="edit-client-dependent",
    ),
    path(
        "edit_client_communication_frequency/<pk>/",
        EditClientCommunicationFrequencyView.as_view(),
        name="edit-client-communication-frequency",
    ),
    path("add_client_note/", AddClientNoteView.as_view(), name="add-client-note",),
    path(
        "edit_client_note/<pk>/", EditClientNoteView.as_view(), name="edit-client-note",
    ),
    path(
        "client_note_list/<pk>/", ClientNoteListView.as_view(), name="client-note-list",
    ),
    path(
        "client_comms_hist/<pk>/",
        UpdateClientCommunicationHistoryView.as_view(),
        name="edit-client-comms",
    ),
]

src/practises/urls.py
from django.urls import path, re_path

from .forms import (
    AddAdministratorContactDetailForm,
    AddAdministratorDetailForm,
    AddAdvisorContactDetailForm,
    AddAdvisorDetailForm,
    AddAdvisorEmploymentForm,
    AddAdvisorProductsForm,
    AddPractiseDetailForm,
    SignUpAdministratorDetailForm,
    SignUpAdvisorDetailForm,
)
from .views import (
    AddAdministratorWizard,
    AddAdvisorWizard,
    AddClientProductView,
    AddPractiseView,
    AddProductView,
    AdministratorlistView,
    AdministratorSummaryView,
    AdvisorlistView,
    AdvisorSearch,
    AdvisorSummaryView,
    EditAdministratorContactView,
    EditAdministratorDetailView,
    EditAdvisorContactView,
    EditAdvisorDetailView,
    EditPractiseView,
    EditProductView,
    EditReminderPreferencesView,
    EditRolesView,
    InviteAdvisor,
    LinkAdvisor,
    ProductlistView,
    SignUpAdministratorWizard,
    SignUpAdvisorWizard,
    ViewClientProductView,
)

app_name = "practises"
urlpatterns = [
    path("add_practise/", AddPractiseView.as_view(), name="add-practise"),
    path("edit_practise/<pk>/", EditPractiseView.as_view(), name="edit-practise"),
    path(
        "advisor/",
        AddAdvisorWizard.as_view(
            [
                AddAdvisorDetailForm,
                AddAdvisorContactDetailForm,
                AddAdvisorEmploymentForm,
                AddAdvisorProductsForm,
            ]
        ),
        name="add-advisor",
    ),
    path(
        "advisor/<int:practise>/",
        AddAdvisorWizard.as_view([AddAdvisorDetailForm, AddAdvisorContactDetailForm]),
        name="add-advisor",
    ),
    path(
        "administrator/",
        AddAdministratorWizard.as_view(
            [AddAdministratorDetailForm, AddAdministratorContactDetailForm]
        ),
        name="add-administrator",
    ),
    path(
        "admin_sign_up/",
        SignUpAdministratorWizard.as_view(
            [
                SignUpAdministratorDetailForm,
                AddAdministratorContactDetailForm,
                AddPractiseDetailForm,
            ]
        ),
        name="sign-up-administrator",
    ),
    path(
        "advisor_sign_up/",
        SignUpAdvisorWizard.as_view(
            [SignUpAdministratorDetailForm, AddAdvisorContactDetailForm]
        ),
        name="sign-up-advisor",
    ),
    path("advisor_list/", AdvisorlistView.as_view(), name="advisor-list"),
    path("advisor_summary/<pk>/", AdvisorSummaryView.as_view(), name="advisor-summary"),
    path(
        "edit_advisor_detail/<pk>/",
        EditAdvisorDetailView.as_view(),
        name="edit-advisor-detail",
    ),
    path(
        "edit_advisor_contact/<pk>/",
        EditAdvisorContactView.as_view(),
        name="edit-advisor-contact",
    ),
    path(
        "administrator_list/",
        AdministratorlistView.as_view(),
        name="administrator-list",
    ),
    path(
        "administrator_summary/<pk>/",
        AdministratorSummaryView.as_view(),
        name="administrator-summary",
    ),
    path(
        "edit_administrator_detail/<pk>/",
        EditAdministratorDetailView.as_view(),
        name="edit-administrator-detail",
    ),
    path(
        "edit_administrator_contact/<pk>/",
        EditAdministratorContactView.as_view(),
        name="edit-administrator-contact",
    ),
    path(
        "edit_advisor_reminder/<pk>/",
        EditReminderPreferencesView.as_view(),
        name="edit-advisor-reminder-config",
    ),
    re_path(r"^search/$", AdvisorSearch, name="advisor-search"),
    path(
        "invite_advisor",
        InviteAdvisor.as_view(),
        name="invite-advisor",
    ),
    path(
        "link_advisor",
        LinkAdvisor.as_view(),
        name="link-advisor",
    ),
    path(
        "edit_advisor_roles/<pk>/",
        EditRolesView.as_view(),
        name="edit-advisor-roles",
    ),
    path("add_product/", AddProductView.as_view(), name="add-product"),
    path("product_list/", ProductlistView.as_view(), name="list-products"),
    path("edit_product/<pk>/", EditProductView.as_view(), name="edit-product"),
    path(
        "view_client_product/<int:client_id>",
        ViewClientProductView.as_view(),
        name="view-client-product",
    ),
    path(
        "add_client_product/",
        AddClientProductView,
        name="add-client-product",
    ),
]

src/clients/models/client_products.py
from django.conf import settings
from django.db import models

from .base import BaseModel


class ClientProduct(BaseModel):
    """
    Class descriptor
    """

    client_id_fk = models.ForeignKey("ClientDetail", on_delete=models.CASCADE)
    product_id_fk = models.ForeignKey(
        "practises.ProductDetail", on_delete=models.CASCADE
    )

src/clients/forms/client_detail.py
from __future__ import unicode_literals

from crispy_forms.helper import FormHelper
from crispy_forms.layout import Column, Field, Layout, Row, Submit
from django import forms
from practises.models import AdvisorDetail

from ..models import ClientDetail


class AddClientDetailForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_tag = False
        self.fields["advisor_id_fk"].label = "Advisor"
        self.fields["names"].label = "First Name"
        self.fields["surnames"].label = "Last Name"

        self.fields["advisor_id_fk"].widget.attrs["class"] = "figly-form-control"
        self.fields["title"].widget.attrs["class"] = "figly-form-control"
        self.fields["initials"].widget.attrs["class"] = "figly-form-control"
        self.fields["names"].widget.attrs["class"] = "figly-form-control"
        self.fields["surnames"].widget.attrs["class"] = "figly-form-control"
        self.fields["sa_id"].widget.attrs["class"] = "figly-form-control"
        self.fields["passport_no"].widget.attrs["class"] = "figly-form-control"

        self.helper.layout = Layout(
            Row(
                Column(
                    "advisor_id_fk",
                    placeholder="Advisor",
                    css_class="form-group col-md-10 ",
                ),
            ),
            Row(
                Column(
                    "title",
                    placeholder="Title",
                    css_class="form-group col-md-5 figly-left-form-input",
                ),
                Column(
                    "initials",
                    placeholder="Initials",
                    css_class="form-group col-md-5 figly-right-form-input",
                ),
            ),
            Row(
                Column(
                    "names", placeholder="Name(s)", css_class="form-group col-md-10"
                ),
            ),
            Row(
                Column(
                    "surnames",
                    placeholder="Surname(s)",
                    css_class="form-group col-md-10",
                ),
            ),
            Row(
                Column(
                    "sa_id",
                    placeholder="RSA ID Number",
                    css_class="form-group col-md-10",
                ),
            ),
            Row(
                Column(
                    "passport_no",
                    placeholder="Passport Number",
                    css_class="form-group col-md-10",
                ),
            ),
        )

    class Meta:
        model = ClientDetail
        fields = [
            "advisor_id_fk",
            "title",
            "initials",
            "surnames",
            "names",
            "known_as",
            "sa_id",
            "passport_no",
        ]

src/clients/forms/client_employment_detail.py
from __future__ import unicode_literals

from django import forms

from crispy_forms.helper import FormHelper
from crispy_forms.layout import Column, Field, Layout, Row, Submit
from practises.models import AdvisorDetail

from ..models import EmploymentDetail


class AddClientEmploymentDetailForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_tag = False
        self.fields["company_name"].widget.attrs["class"] = "figly-form-control"
        self.fields["employment_date"].widget.attrs[
            "class"
        ] = "figly-form-control datepicker"
        self.fields["personnel_number"].widget.attrs["class"] = "figly-form-control"
        self.fields["medical_aid"].widget.attrs["class"] = "figly-form-control"
        self.fields["retirement_fund_current_value"].widget.attrs[
            "class"
        ] = "figly-form-control"
        self.fields["group_life_cover"].widget.attrs["class"] = "figly-form-control"

        self.helper.layout = Layout(
            Row(
                Column(
                    "company_name",
                    placeholder="Company",
                    css_class="form-group col-md-10",
                ),
            ),
            Row(
                Column(
                    "employment_date",
                    placeholder="Employment Date",
                    css_class="form-group col-md-10",
                ),
            ),
            Row(
                Column(
                    "personnel_number",
                    placeholder="Personnel Number",
                    css_class="form-group col-md-10",
                ),
            ),
            Row(
                Column(
                    "medical_aid",
                    placeholder="Medical Aid",
                    css_class="form-group col-md-10",
                ),
            ),
            Row(
                Column(
                    "retirement_fund_current_value",
                    placeholder="Retirement Fund Current Value",
                    css_class="form-group col-md-10",
                ),
            ),
            Row(
                Column(
                    "group_life_cover",
                    placeholder="Group Life Cover",
                    css_class="form-group col-md-10",
                ),
            ),
        )

    class Meta:
        model = EmploymentDetail
        fields = [
            "company_name",
            "employment_date",
            "personnel_number",
            "medical_aid",
            "retirement_fund_current_value",
            "group_life_cover",
        ]

src/clients/views/communication.py
import logging
from datetime import datetime

from django import forms
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import JsonResponse
from django.http.response import HttpResponseRedirect
from django.shortcuts import get_object_or_404
from django.urls import reverse, reverse_lazy
from django.views import generic

from ..forms import UpdateClientCommunicationHistory
from ..models import ClientCommunication, ClientCommunicationFrequency

log = logging.getLogger(__name__)


class EditClientCommunicationFrequencyView(LoginRequiredMixin, generic.UpdateView):
    template_name = "clients/edit_details.html"
    model = ClientCommunicationFrequency
    fields = (
        "face_to_face_frequency",
        "calls_frequency",
        "email_frequency",
        "sms_frequency",
    )

    def form_valid(self, form):
        if "cancel" in self.request.POST:
            url = reverse_lazy("home")
            return HttpResponseRedirect(url)

        model = form.save(commit=False)
        model.modified_by = self.request.user
        model.save

        messages.add_message(
            self.request,
            messages.SUCCESS,
            "client communication frequency successfully edited.",
        )
        self.success_url = reverse_lazy("home")
        return super(EditClientCommunicationFrequencyView, self).form_valid(form)


class UpdateClientCommunicationHistoryView(LoginRequiredMixin, generic.UpdateView):
    template_name = "clients/edit_details.html"
    model = ClientCommunication
    form_class = UpdateClientCommunicationHistory

    def form_valid(self, form):
        home = reverse_lazy("home")

        if "cancel" in self.request.POST:
            return HttpResponseRedirect(home)

        model = form.save(commit=False)

        today = datetime.date.today()
        if (
            model.last_date_email > today
            or model.last_date_sms > today
            or model.last_date_call > today
            or model.last_date_face_to_face > today
        ):
            messages.add_message(
                self.request, messages.ERROR, "Dates cannot be in the future.",
            )
            return HttpResponseRedirect(self.request.path_info)

        model.modified_by = self.request.user
        model.save

        messages.add_message(
            self.request,
            messages.SUCCESS,
            "client communication history successfully updated.",
        )
        self.success_url = home
        return super(UpdateClientCommunicationHistoryView, self).form_valid(form)


class UpdateLastSeen(generic.View):
    def post(self, request, *args, **kwargs):
        try:
            client_comms_id = request.POST.get("client_comms_id", None)
            date_value = request.POST.get("date_value")

            if client_comms_id is None:
                return JsonResponse({"valid": False}, status=400)

            clientComms = get_object_or_404(ClientCommunication, pk=client_comms_id)
            clientComms.last_contacted = date_value

            clientComms.save()

            return JsonResponse({"valid": True}, status=200)
        except Exception as e:
            log.info(e)
            return JsonResponse(
                {"valid": "An error occured. Please contact an administrator"},
                status=400,
            )

src/clients/templates/clients/add_client_contact_detail.html
{% extends "base.html" %}
{% load i18n %}
{% block head %}
{{ wizard.form.media }}
{% load crispy_forms_tags %}
{% endblock %}
{% block content %}
{% block container %}
<div class="container">
  <div class="row">
    <div>
      <p class="figly-form-heading">ADD CLIENT</p>
    </div>
  </div>
  <hr style=" margin: 0px 0px 36px 50px;" />
</div>
<div class="container figly-container-main">
  <div class="row">
    <div class="col-md-3 client-stepper">
      <div class="vl"></div>
      <div class="step step-active">
        <div>
          <div class="circle"></div>
        </div>
        <div>
          <div class="title">Personal details</div>
          <div class="caption"></div>
        </div>
      </div>
      <div class="vl"></div>
      <div class="step step-active">
        <div>
          <div class="circle"></div>
        </div>
        <div>
          <div class="title">Contact details</div>
        </div>
      </div>
      <div class="vl"></div>
      <div class="step">
        <div>
          <div class="circle"></div>
        </div>
        <div>
          <div class="title">Employment details</div>
        </div>
      </div>
      <div class="vl"></div>
      <div class="step">
        <div>
          <div class="circle"></div>
        </div>
        <div>
          <div class="title">Financial details</div>
        </div>
      </div>
      <div class="vl"></div>
      <div class="step">
        <div>
          <div class="circle"></div>
        </div>
        <div>
          <div class="title">Products</div>
        </div>
      </div>
      <div class="vl"></div>
    </div>
    <div class="col-md-7">
      <div class="container">
        {% comment %} <p class="figly-heading figly-heading-h1 client-register-heading">CLIENT DETAILS</p>
        <hr /> {% endcomment %}
        <form action="" method="POST">{% csrf_token %}
          {{ wizard.management_form }}
          {% if wizard.form.forms %}
          {{ wizard.form.management_form }}
          {% for form in wizard.form.forms %}
          {% crispy form %}
          {% endfor %}
          {% else %}
          {% crispy wizard.form %}
          {% endif %}
          <div class="form-row">
            {% if wizard.steps.prev %}
            <div class="col-md-5 figly-left-form-input form-group">
              <button name="wizard_goto_step" formnovalidate value="{{ wizard.steps.prev }}"
                class="btn figly-btn-secondary ">{% trans "Back" %}
              </button>
            </div>
            {% endif %}
            <div class="col-md-5 figly-right-form-input form-group">
              <button type="submit" class="btn figly-btn-wizard-next ">{% trans "Continue" %}
              </button>
            </div>
          </div>
        </form>
      </div>
       <div class="container">
         <hr class="figly-form-hr" />
          <div class="text-align-center">
          <a class="form-cancel" href="/">Cancel</a>
          </div>
      </div>
    </div>
  </div>
</div>

{% block footer %}
{% include "footer.html" %}
{% endblock footer %}

{% endblock %}
{% endblock %}
</script>
{% block scripts %}
<script type='text/javascript'>
  $(document).ready(function () {
    $("#same-as-residential").click(function () {
      if ($(this).is(':checked')) {
        $("#postal-line-1-id").val($("#residential-line-1-id").val());
        $("#postal-line-2-id").val($("#residential-line-2-id").val());
        $("#postal-code-id").val($("#residential-code-id").val());
      } else {
        $("#postal-line-1-id").val("");
        $("#postal-line-2-id").val("");
        $("#postal-code-id").val("");
      }
    });
  });
</script>
{% endblock scripts %}

src/clients/templates/clients/add_client_note.html
{% extends "base.html" %}

{% load crispy_forms_tags %}

{% block container %}
  <div class="container">
    <h3>Client Note </h3>
    <form action="" method="POST">
      {% csrf_token %}
      {% crispy form %}
      <button type="submit" name="submit" class="btn btn-primary btn-lg">Submit</button>
      <button type="submit" name="add-another" class="btn btn-success btn-lg" style="width: 120px;">Add Another</button>
    </form>
  </div>
{% endblock %}

src/clients/templates/clients/advisor_clients.html
{% load i18n %}

{% block content %}
{% block container %}
{% if clients %}

<div class="table_detail_rows">
    <table class="table sortable-table">
     <thead>
        <tr>
            <th scope="col" class="sort_list_alphabetically"> Name
            </th>
            <th scope="col" class="sort_list_alphabetically">Email
            </th>
            <th scope="col">Cellphone
            </th>
            <th scope="col" class="sort_list_alphabetically">Location
            </th>
            <th scope="col">Last Contact
            </th>
            <th scope="col">Status
            </th>
        </tr>
      </thead>
        {% load client_status %}
        {% for client in clients %}

            <tr class="client-data-body" scope="row" data-href="{% url 'clients:client-summary' pk=client.id %}">

                <td><a href="{% url 'clients:client-summary' pk=client.id %}">{{ client.names }} {{ client.surnames }}</a>
                </td>
                <td><a href="{% url 'clients:client-summary' pk=client.id %}">{{ client.client_contact_fk.email_address }}</a>
                </td>
                <td><a href="{% url 'clients:client-summary' pk=client.id %}">{{ client.client_contact_fk.cellphone_number }}</a>
                </td>
                <td><a href="{% url 'clients:client-summary' pk=client.id %}">{{ client.client_contact_fk.residential_city }}</a>
                </td>
                <td><input class="datepicker last-contact-date-input" date-format='yyyy-mm-dd'  id={{client.client_comms_fk.id}} value = "{{ client.client_comms_fk.last_contacted }}">
                    <button class="last-contact-update-btn" onclick="updateComms(this)" role="button" data-id={{client.client_comms_fk.id}}>
                        <i class="fa fa-refresh update-last-contact" aria-hidden="true">
                            <span>UPDATE</span>
                        </i>
                    </button>
                </td>
                <td><a class={% client_status client.client_comms_fk.last_contacted %}  href="{% url 'clients:client-summary' pk=client.id %}">{% client_status client.client_comms_fk.last_contacted %}</a>
                </td>
                {% if user.is_superuser %}
                <td>{{ client.advisor_id_fk.practise_id_fk}}</td>
                <td>{{ client.advisor_id_fk}}</td>
                {% endif %}
                {%if user.is_administrator %}
                <td>{{client.employment_date}}</td>
                {% endif %}
            </tr>
        {% endfor %}
    </table>
</div>
{% else %}
<p>No Clients to Display</p>
{% endif %}
{% endblock %}
{% endblock %}

{% block scripts %}
<script type='text/javascript'>
$(function(){
$('.input-group.date').datepicker({
    calendarWeeks: true,
    todayHighlight: true,
    autoclose: true
});
});

</script>
  <script>
function updateComms(e){
    var client_comms_id = e.getAttribute('data-id');
    var dateValue = convertDate(new Date(document.getElementById(client_comms_id).value));
    $.ajax({
        type: 'POST',
        headers:{
        "X-CSRFToken": '{{ csrf_token }}'
        },
        url: "{% url 'clients:update-comms'%}",
        data: {'client_comms_id':client_comms_id, 'date_value': dateValue},
        success: function (response) {
            e.value = dateValue
            location.reload();
        },
        error: function (response) {
        }
    });
}
function convertDate(date) {
  var yyyy = date.getFullYear().toString();
  var mm = (date.getMonth()+1).toString();
  var dd  = date.getDate().toString();

  var mmChars = mm.split('');
  var ddChars = dd.split('');

  return yyyy + '-' + (mmChars[1]?mm:"0"+mmChars[0]) + '-' + (ddChars[1]?dd:"0"+ddChars[0]);
}
</script>
{% endblock %}

src/clients/templates/clients/client_list.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}
{% block container %}
<div class="container">
  <h1>Client List</h1>
    {% if clients %}
    <table class="table">
        <thead>
            <tr>
                <th scope="col">ID</th>
                <th scope="col">Name</th>
                <th scope="col">Surname</th>
                <th scope="col">Email</th>
                {%if user.is_superuser %}
                <th scope="col">Practise</th>
                <th scope="col">Advisor</th>
                {% endif %}
                {%if user.is_administrator %}
                <th scope="col">Advisor</th>
                {% endif %}
                <th scope="col">Notes</th>
                <th scope="col">Communication</th>
                <th scope="col">Link Products</th>
            </tr>
        </thead>
        {% for client in clients %}
        <tbody>
            <tr scope="row">
                <td>{{ client.id }}</td>
                <td><a href="{% url 'clients:client-summary' pk=client.id %}">{{ client.names }}</a></td>
                <td>{{ client.surnames }}</td>
                <td>{{ client.client_contact_fk.email_address }}</td>
                {% if user.is_superuser %}
                <td>{{ client.advisor_id_fk.practise_id_fk}}</td>
                <td>{{ client.advisor_id_fk}}</td>
                {% endif %}
                {%if user.is_administrator %}
                <td>{{ client.advisor_id_fk}}</td>
                {% endif %}
                <td><a href="{% url 'clients:client-note-list' pk=client.id %}">Notes ({{ client.notes.count }})</a></td>
                <td><a href="{% url 'clients:edit-client-comms' pk=client.client_comms_fk.id %}"><span class="glyphicon glyphicon-pencil"></a></td>
                <td><a href="{% url 'practises:view-client-product' client_id=client.id %}" style="color: green;"><span class="glyphicon glyphicon-plus"></a></td>
            </tr>
        </tbody>
        {% endfor %}
    </table>
    {% else %}
    <p>No Clients to Display</p>
</div>
  {% endif %}
{% endblock %}
{% endblock %}

src/clients/templates/clients/client_note_list.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}
{% block container %}
<div class="container">
  <h1>Notes List</h1>
  <h2>{{client}}</h2>
  <h3><a href="{% url 'clients:add-client-note'%}"> Add Notes </a></h3>
    {% if notes %}
    <table class="table">
        <thead>
            <tr>
                <th scope="col">ID</th>
                <th scope="col">Title</th>
                <th scope="col">Body</th>
                <th scope="col">Type</th>
                <th scope="col">Created Date</th>
                <th scope="col">Last Modified by</th>
            </tr>
        </thead>
        {% for note in notes %}
        <tbody>
            <tr scope="row">
                <td>{{ note.id }}</td>
                <td><a href="{% url 'clients:edit-client-note' pk=note.id %}">{{ note.title }}</a></td>
                <td>{{ note.body }}</td>
                <td>{{ note.note_type }}</td>
                <td>{{ note.created_at }}</td>
                <td>{{ note.modified_by }}</td>
            </tr>
        </tbody>
        {% endfor %}
    </table>
    {% else %}
    <p>No Notes to Display</p>
</div>
  {% endif %}
{% endblock %}
{% endblock %}

src/clients/templates/clients/clients_list.html
{% load i18n %}

{% block content %}
{% block container %}
{% if clients %}

<div class="table_detail_rows">
    <table class="table sortable-table">
        <thead>
            <tr>
                <th scope="col" class="sort_list_alphabetically">Name</th>
                <th scope="col" class="sort_list_alphabetically">Email</th>
                <th scope="col" class="sort_list_alphabetically">Location</th>
                <th scope="col">Cellphone </th>
                <th scope="col" class="numeric-sort">Last Visit</th>
                {% comment %} <th scope="col">Surname</th> {% endcomment %}
                {% comment %} {%if user.is_superuser %}
                <th scope="col">Email</th>
                <th scope="col">Advisor</th>
                {% endif %}
                {%if user.is_administrator %}
                <th scope="col">Advisor</th>
                {% endif %} {% endcomment %}
                
            </tr>
        </thead>
        {% for client in clients %}
            <tr scope="row"  class="client-data-body" >
                <td ><a href="{% url 'clients:client-summary' pk=client.id %}">{{ client.names }} {{ client.surnames }}</a>
                </td>              
                <td> <ahref="{% url 'clients:client-summary' pk=client.id %}">{{ client.client_contact_fk.email_address }}</a>
                </td>
                <td><a href="{% url 'clients:client-summary' pk=client.id %}">{{ client.client_contact_fk.residential_city }}</a>
                </td>
                <td><a href="{% url 'clients:client-summary' pk=client.id %}">{{ client.client_contact_fk.cellphone_number }}</a>
                </td> 
                <td><a href="{% url 'clients:client-summary' pk=client.id %}">{{ client.client_employment_fk.employment_date }}</a>
                </td>
                {% if user.is_superuser %}
                <td>{{ client.advisor_id_fk.practise_id_fk}}</td>
                <td>{{ client.advisor_id_fk}}</td>
                {% endif %}
                {%if user.is_administrator %}
                <td>{{client.employment_date}}</td>
                {% endif %}
            </tr>
        {% endfor %}
    </table>
</div>
{% else %}
<p>No Clients to Display</p>

{% endif %}
{% endblock %}
{% endblock %}