src/ayama/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path, re_path

import accounts.urls
import clients.urls
import practises.urls
import profiles.urls
import calculator.urls

from . import views

# Personalized admin site settings like title and header
admin.site.site_title = "Ayama Site Admin"
admin.site.site_header = "Ayama Administration"

urlpatterns = [
    re_path(r"^healthz/", views.healthz, name="healthz"),
    path("", views.HomePage.as_view(), name="home"),
    path("about/", views.AboutPage.as_view(), name="about"),
    path("users/", include(profiles.urls)),
    path("admin/", admin.site.urls),
    path("", include(accounts.urls)),
    path("", include(practises.urls)),
    path("", include(clients.urls)),
    path("calcs/", include(calculator.urls)),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [path("__debug__/", include(debug_toolbar.urls))]

    # Dev ref for profile pics -- should probably redo this at some point
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/practises/urls.py
from django.urls import path, re_path

from .forms import (
    AddAdministratorContactDetailForm,
    AddAdministratorDetailForm,
    AddAdvisorContactDetailForm,
    AddAdvisorDetailForm,
    AddAdvisorEmploymentForm,
    AddAdvisorProductsForm,
    AddPractiseDetailForm,
    SignUpAdministratorDetailForm,
    SignUpAdvisorDetailForm,
)
from .views import (
    AddAdministratorWizard,
    AddAdvisorWizard,
    AddClientProductView,
    AddPractiseView,
    AddProductView,
    AdministratorlistView,
    AdministratorSummaryView,
    AdvisorlistView,
    AdvisorSearch,
    AdvisorSummaryView,
    EditAdministratorContactView,
    EditAdministratorDetailView,
    EditAdvisorContactView,
    EditAdvisorDetailView,
    EditPractiseView,
    EditProductView,
    EditReminderPreferencesView,
    EditRolesView,
    InviteAdvisor,
    LinkAdvisor,
    ProductlistView,
    SignUpAdministratorWizard,
    SignUpAdvisorWizard,
    ViewClientProductView,
)

app_name = "practises"
urlpatterns = [
    path("add_practise/", AddPractiseView.as_view(), name="add-practise"),
    path("edit_practise/<pk>/", EditPractiseView.as_view(), name="edit-practise"),
    path(
        "advisor/",
        AddAdvisorWizard.as_view(
            [
                AddAdvisorDetailForm,
                AddAdvisorContactDetailForm,
                AddAdvisorEmploymentForm,
                AddAdvisorProductsForm,
            ]
        ),
        name="add-advisor",
    ),
    path(
        "advisor/<int:practise>/",
        AddAdvisorWizard.as_view([AddAdvisorDetailForm, AddAdvisorContactDetailForm]),
        name="add-advisor",
    ),
    path(
        "administrator/",
        AddAdministratorWizard.as_view(
            [AddAdministratorDetailForm, AddAdministratorContactDetailForm]
        ),
        name="add-administrator",
    ),
    path(
        "admin_sign_up/",
        SignUpAdministratorWizard.as_view(
            [
                SignUpAdministratorDetailForm,
                AddAdministratorContactDetailForm,
                AddPractiseDetailForm,
            ]
        ),
        name="sign-up-administrator",
    ),
    path(
        "advisor_sign_up/",
        SignUpAdvisorWizard.as_view(
            [SignUpAdministratorDetailForm, AddAdvisorContactDetailForm]
        ),
        name="sign-up-advisor",
    ),
    path("advisor_list/", AdvisorlistView.as_view(), name="advisor-list"),
    path("advisor_summary/<pk>/", AdvisorSummaryView.as_view(), name="advisor-summary"),
    path(
        "edit_advisor_detail/<pk>/",
        EditAdvisorDetailView.as_view(),
        name="edit-advisor-detail",
    ),
    path(
        "edit_advisor_contact/<pk>/",
        EditAdvisorContactView.as_view(),
        name="edit-advisor-contact",
    ),
    path(
        "administrator_list/",
        AdministratorlistView.as_view(),
        name="administrator-list",
    ),
    path(
        "administrator_summary/<pk>/",
        AdministratorSummaryView.as_view(),
        name="administrator-summary",
    ),
    path(
        "edit_administrator_detail/<pk>/",
        EditAdministratorDetailView.as_view(),
        name="edit-administrator-detail",
    ),
    path(
        "edit_administrator_contact/<pk>/",
        EditAdministratorContactView.as_view(),
        name="edit-administrator-contact",
    ),
    path(
        "edit_advisor_reminder/<pk>/",
        EditReminderPreferencesView.as_view(),
        name="edit-advisor-reminder-config",
    ),
    re_path(r"^search/$", AdvisorSearch, name="advisor-search"),
    path(
        "invite_advisor",
        InviteAdvisor.as_view(),
        name="invite-advisor",
    ),
    path(
        "link_advisor",
        LinkAdvisor.as_view(),
        name="link-advisor",
    ),
    path(
        "edit_advisor_roles/<pk>/",
        EditRolesView.as_view(),
        name="edit-advisor-roles",
    ),
    path("add_product/", AddProductView.as_view(), name="add-product"),
    path("product_list/", ProductlistView.as_view(), name="list-products"),
    path("edit_product/<pk>/", EditProductView.as_view(), name="edit-product"),
    path(
        "view_client_product/<int:client_id>",
        ViewClientProductView.as_view(),
        name="view-client-product",
    ),
    path(
        "add_client_product/",
        AddClientProductView,
        name="add-client-product",
    ),
]

src/clients/models/client_communication.py
from django.db import models

from .base import BaseModel


class ClientCommunication(BaseModel):
    """
    Class descriptor
    """

    last_date_email = models.DateField(
        "Last date email",
        auto_now=False,
        auto_now_add=False,
        default=None,
        blank=True,
        null=True,
    )

    last_date_sms = models.DateField(
        "Last date SMS",
        auto_now=False,
        auto_now_add=False,
        default=None,
        blank=True,
        null=True,
    )
    last_date_call = models.DateField(
        "Last date call",
        auto_now=False,
        auto_now_add=False,
        default=None,
        blank=True,
        null=True,
    )
    last_date_face_to_face = models.DateField(
        "Last date face to face",
        auto_now=False,
        auto_now_add=False,
        default=None,
        blank=True,
        null=True,
    )
    last_contacted = models.DateField(
        "Last date contacted",
        auto_now=False,
        auto_now_add=False,
        default=None,
        blank=True,
        null=True,
    )

    def __str__(self):
        """Return a human readable representation of the model instance."""
        return f"{self.last_date_email} {self.last_date_call}"


class ClientCommunicationFrequency(BaseModel):
    """
    Class descriptor
    """

    face_to_face_frequency = models.IntegerField(blank=True, null=True)
    calls_frequency = models.IntegerField(blank=True, null=True)
    email_frequency = models.IntegerField(blank=True, null=True)
    sms_frequency = models.IntegerField(blank=True, null=True)

    def __str__(self):
        """Return a human readable representation of the model instance."""
        return f"{self.face_to_face_frequency} {self.email_frequency}"

src/practises/views/administrator.py
from __future__ import unicode_literals

import logging

from django.contrib import messages
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.db import transaction
from django.db.models import Q
from django.forms.models import construct_instance
from django.http.response import HttpResponseRedirect
from django.urls import reverse_lazy
from django.views import generic
from formtools.wizard.views import SessionWizardView

from ..forms import AddAdministratorContactDetailForm, AddAdministratorDetailForm
from ..models import AdministratorContactDetail, AdministratorDetail

FORMS = [
    ("0", AddAdministratorDetailForm),
    ("1", AddAdministratorContactDetailForm),
]

TEMPLATES = {
    "0": "practises/add_administrator.html",
    "1": "practises/add_administrator_contact_detail.html",
}
log = logging.getLogger(__name__)


class AddAdministratorWizard(
    LoginRequiredMixin, UserPassesTestMixin, SessionWizardView
):
    def test_func(self):
        return self.request.user.is_superuser

    def get_template_names(self):
        return TEMPLATES[self.steps.current]

    def get_context_data(self, form, **kwargs):
        context = super(AddAdministratorWizard, self).get_context_data(
            form=form, **kwargs
        )
        if self.steps.current != "0":
            administrator_name = []
            step0data = self.get_cleaned_data_for_step("0")
            administrator_name.append(step0data["title"].capitalize())
            administrator_name.append(step0data["initials"].capitalize())
            administrator_name.append(step0data["surnames"].capitalize())
            context.update({"administrator_name": " ".join(administrator_name)})
        return context

    @transaction.atomic
    def done(self, form_list, form_dict, **kwargs):
        try:
            # models backing db
            administrator = AdministratorDetail()
            administratorContactDetail = AdministratorContactDetail()
            User = get_user_model()

            # form instances
            administrator = construct_instance(
                form_dict["0"],
                administrator,
                form_dict["0"]._meta.fields,
                form_dict["0"]._meta.exclude,
            )

            administratorContactDetail = construct_instance(
                form_dict["1"],
                administratorContactDetail,
                form_dict["1"]._meta.fields,
                form_dict["1"]._meta.exclude,
            )

            existing_user = User.objects.filter(
                Q(email=administratorContactDetail.email_address)
                | Q(username=administratorContactDetail.email_address)
            )

            if not existing_user:
                User = User.objects.create_user(
                    email=administratorContactDetail.email_address,
                    username=administratorContactDetail.email_address,
                    password="password",
                    first_name=administrator.names,
                    last_name=administrator.surnames,
                    name=administrator.names + " " + administrator.surnames,
                )  # default password for now, to revise

                User.is_advisor = False
                User.is_administrator = True
                User.is_staff = True
                User.is_superuser = False
                User.save()
                administrator.user = User

                administratorContactDetail.modified_by = self.request.user
                administratorContactDetail.save()
                administrator.adminstrator_contact_fk = administratorContactDetail

                administrator.modified_by = self.request.user
                administrator.save()

                messages.add_message(
                    self.request, messages.SUCCESS, "administrator successfully added."
                )
            else:
                messages.add_message(
                    self.request, messages.ERROR, "Email address already in use."
                )
                return HttpResponseRedirect(self.request.path_info)
        except Exception as e:
            log.info(e)
            messages.add_message(
                self.request, messages.ERROR, "An error occured. Please try again."
            )
            return HttpResponseRedirect(reverse_lazy("home"))

        return HttpResponseRedirect(reverse_lazy("home"))


class AdministratorlistView(LoginRequiredMixin, UserPassesTestMixin, generic.ListView):
    template_name = "practises/administrator_list.html"
    model = AdministratorDetail

    def test_func(self):
        return self.request.user.is_superuser

    def get_context_data(self, **kwargs):
        context = super(AdministratorlistView, self).get_context_data(**kwargs)
        user = self.request.user
        if user.is_superuser:
            administrators = AdministratorDetail.objects.all().select_related(
                "adminstrator_contact_fk"
            )
            context = {"administrators": administrators}
        elif user.is_superuser:
            return HttpResponseRedirect(reverse_lazy("home"))

        return context


class AdministratorSummaryView(
    LoginRequiredMixin, UserPassesTestMixin, generic.DetailView
):
    template_name = "practises/administrator_summary.html"
    model = AdministratorDetail

    def test_func(self):
        return self.request.user.is_superuser

    def get_context_data(self, **kwargs):
        context = super(AdministratorSummaryView, self).get_context_data(**kwargs)
        administrator_id = self.kwargs["pk"]
        administrator = AdministratorDetail.objects.get(user=administrator_id)
        context = {"administrator": administrator}
        return context


class EditAdministratorDetailView(
    LoginRequiredMixin, UserPassesTestMixin, generic.UpdateView
):
    template_name = "practises/edit_administrator_detail.html"
    model = AdministratorDetail
    fields = (
        "title",
        "initials",
        "surnames",
        "names",
        "known_as",
        "sa_id",
        "passport_no",
        "position",
        "employment_date",
        "personnel_number",
    )

    def test_func(self):
        return self.request.user.is_superuser

    def form_valid(self, form):
        if "cancel" in self.request.POST:
            url = reverse_lazy("home")
            return HttpResponseRedirect(url)

        model = form.save(commit=False)
        model.modified_by = self.request.user
        model.save

        messages.add_message(
            self.request, messages.SUCCESS, "administrator details successfully edited."
        )
        self.success_url = reverse_lazy("home")
        return super(EditAdministratorDetailView, self).form_valid(form)


class EditAdministratorContactView(
    LoginRequiredMixin, UserPassesTestMixin, generic.UpdateView
):
    template_name = "practises/edit_administrator_detail.html"
    model = AdministratorContactDetail
    fields = (
        "telephone_home",
        "telephone_work",
        "cellphone_number",
        "fax_number",
        "email_address",
        "residential_address_line_1",
        "residential_address_line_2",
        "residential_suburb",
        "residential_city",
        "residential_country",
        "residential_code",
        "postal_address_line_1",
        "postal_address_line_2",
        "postal_suburb",
        "postal_city",
        "postal_country",
        "postal_code",
    )

    def test_func(self):
        return self.request.user.is_superuser

    def form_valid(self, form):
        if "cancel" in self.request.POST:
            url = reverse_lazy("home")
            return HttpResponseRedirect(url)

        model = form.save(commit=False)
        model.modified_by = self.request.user
        model.save

        messages.add_message(
            self.request,
            messages.SUCCESS,
            "administrator contact details successfully edited.",
        )
        self.success_url = reverse_lazy("home")
        return super(EditAdministratorContactView, self).form_valid(form)

src/practises/views/practise.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.http.response import HttpResponseRedirect
from django.urls import reverse_lazy
from django.views import generic

from .. import forms, models


class AddPractiseView(LoginRequiredMixin, UserPassesTestMixin, generic.CreateView):
    template_name = "practises/add_practise_detail.html"
    form_class = forms.AddPractiseDetailForm
    model = models.PractiseDetail

    def test_func(self):
        return self.request.user.is_administrator or self.request.user.is_superuser

    def form_valid(self, form):
        model = form.save(commit=False)
        model.modified_by = self.request.user
        model.save()

        messages.add_message(
            self.request, messages.SUCCESS, "practise successfully added."
        )

        if "add-advisor" in self.request.POST:
            self.success_url = reverse_lazy(
                "practises:add-advisor", kwargs={"practise": model.id}
            )
        elif "submit" in self.request.POST:
            self.success_url = reverse_lazy("home")

        return super(AddPractiseView, self).form_valid(form)


class EditPractiseView(LoginRequiredMixin, UserPassesTestMixin, generic.UpdateView):
    template_name = "practises/edit_practise_detail.html"
    model = models.PractiseDetail
    fields = (
        "name",
        "residential_address_line_1",
        "residential_address_line_2",
        "residential_code",
        "postal_address_line_1",
        "postal_address_line_2",
        "postal_code",
    )

    def test_func(self):
        return self.request.user.is_administrator or self.request.user.is_superuser

    def form_valid(self, form):
        if "cancel" in self.request.POST:
            url = reverse_lazy("home")
            return HttpResponseRedirect(url)

        model = form.save(commit=False)
        model.modified_by = self.request.user
        model.save

        messages.add_message(
            self.request, messages.SUCCESS, "practise successfully edited."
        )
        self.success_url = reverse_lazy("home")
        return super(EditPractiseView, self).form_valid(form)

src/practises/templates/practises/add_administrator_contact_detail.html
{% extends "base.html" %}
{% load i18n %}

{% block head %}
{{ wizard.form.media }}
{% load crispy_forms_tags %}
{% endblock %}

{% block content %}
{% block container %}
  <div class="container">
    <form action="" method="POST">{% csrf_token %}
      <p>Step {{ wizard.steps.step1 }} of {{ wizard.steps.count }}</p>
      <nav aria-label="breadcrumb">
        <ol class="breadcrumb remove_breadcrumb_css">
          <li class="breadcrumb-item"><button  class="btn btn-link remove_breadcrumb_btn_css" formnovalidate role="link" name="wizard_goto_step" value="{{ wizard.steps.first }}">Administrator Details</button></li>
          <li class="breadcrumb-item active" aria-current="page">Contact details</li>
        </ol>
      </nav>
      <h3>Administrator Contact Detail  {{ administrator_name }}</h3>
      {{ wizard.management_form }}
      {% if wizard.form.forms %}
        {{ wizard.form.management_form }}
        {% for form in wizard.form.forms %}
          {% crispy form %}
        {% endfor %}
      {% else %}
        {% crispy wizard.form %}
      {% endif %}
      <div class="row">
        <div class="text-center">
          {% if wizard.steps.prev %}
          <button name="wizard_goto_step" formnovalidate value="{{ wizard.steps.prev }}" class="btn btn-secondary btn-lg">{% trans "Previous" %}</button>
          {% endif %}
          <button type="submit" class="btn btn-primary btn-lg">{% trans "Done" %}</button>
        </div>
      </div>
    </form>
  </div>
{% endblock %}

{% endblock %}

src/practises/templates/practises/add_practise_detail.html
{% extends "base.html" %}

{% load crispy_forms_tags %}

{% block container %}
  <div class="container">
    <h3>Practise Details</h3>
    <form action="" method="POST">
      {% csrf_token %}
      {% crispy form %}
      <button type="submit" name="submit" class="btn btn-primary btn-lg">Submit</button>
      <button type="submit" name="add-advisor" class="btn btn-success btn-lg" style="width: 100px;">Link Advisor</button>
    </form>
  </div>
{% endblock %}

src/practises/templates/practises/add_product_detail.html
{% extends "base.html" %}
{% load i18n %}

{% block head %}
{% load crispy_forms_tags %}
{% endblock %}

{% block content %}
{% block container %}
    <div class="container">
      <h3>Product Details</h3>
      <form action="" method="POST">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" name="submit" class="btn btn-primary btn-lg">Submit</button>
      </form>
    </div>
{% endblock %}
{% endblock %}

src/practises/templates/practises/administrator_summary.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}
{% block container %}
    {% if administrator %}
    <div class="container" style="font-size: larger;" >
        <h1>Administrator Details</h1>
        <div class="container">
            <div class="row">
                <div class="col-md-12 col-sm-12">
                    <div class="col-md-6 col-sm-6">
                        <h2>Personal Details</h2>
                    </div>
                    <div class="col-md-6 col-sm-6">
                        <a href="{% url 'practises:edit-administrator-detail' pk=administrator.user_id %}"><span class="glyphicon glyphicon-pencil icon-edit-customer"></a>
                    </div>
                </div>
                <div class="col-md-6 col-sm-6">
                        <p><strong>Title:</strong></p> {{administrator.title}}
                        <p><strong>Name:</strong></p> {{administrator.names}}
                        <p><strong>Surname:</strong></p> {{administrator.surnames}}
                        <p><strong>Known as:</strong></p> {{administrator.known_as}}
                        <p><strong>ID number:</strong></p> {{administrator.sa_id}}
                        <p><strong>Passport No:</strong></p> {{administrator.passport_no}}
                </div>
                <div class="col-md-6 col-sm-6">
                    <p><strong>Position:</strong></p> {{administrator.position}}
                    <p><strong>Employment Date:</strong></p> {{administrator.employment_date}}
                    <p><strong>Personnel No:</strong></p> {{administrator.personnel_number}}
                </div>
            </div>
            <div class="row">
                <div class="col-md-12 col-sm-12">
                    <div class="col-md-6 col-sm-6">
                        <h2>Contact Details</h2>
                    </div>
                    <div class="col-md-6 col-sm-6">
                        <a href="{% url 'practises:edit-administrator-contact' pk=administrator.adminstrator_contact_fk.id %}"><span class="glyphicon glyphicon-pencil icon-edit-customer"></a>
                    </div>
                </div>
                <div class="col-md-6 col-sm-6">
                        <p><strong>Telephone home:</strong></p> {{administrator.adminstrator_contact_fk.telephone_home}}
                        <p><strong>Telephone work:</strong></p> {{administrator.adminstrator_contact_fk.telephone_work}}
                        <p><strong>Cellphone:</strong></p> {{administrator.adminstrator_contact_fk.cellphone_number}}
                        <p><strong>Postal Address:</strong></p> {{administrator.adminstrator_contact_fk.postal_address_line_1}}
                </div>
                <div class="col-md-6 col-sm-6">
                    <p><strong>Fax Number:</strong></p> {{administrator.adminstrator_contact_fk.fax_number}}
                    <p><strong>Email Address:</strong></p> {{administrator.adminstrator_contact_fk.email_address}}
                    <p><strong>Residential Address:</strong></p> {{administrator.adminstrator_contact_fk.residential_address_line_1}}
                </div>
            </div>
        </div>
</div>
  {% endif %}
{% endblock %}
{% endblock %}

src/practises/templates/practises/advisor_list.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}
{% block container %}
<div class="container">
  <h1>Advisor List</h1>
    {% if advisors %}
    <table class="table">
        <thead>
            <tr>
                <th scope="col">Name</th>
                <th scope="col">Surname</th>
                <th scope="col">Email</th>
                <th scope="col">ID Number</th>
                <th scope="col">Tel Home</th>
                <th scope="col">Cellphone</th>
                <th scope="col">Is Administrator</th>
            </tr>
        </thead>
        {% for advisor in advisors %}
        <tbody>
            <tr scope="row">
                <td><a href="{% url 'practises:advisor-summary' pk=advisor.user_id %}">{{ advisor.names }}</a></td>
                <td>{{ advisor.surnames }}</td>
                <td>{{ advisor.advisor_contact_fk.email_address }}</td>
                <td>{{ advisor.sa_id}}</td>
                <td>{{ advisor.advisor_contact_fk.telephone_home }}</td>
                <td>{{ advisor.advisor_contact_fk.cellphone_number }}</td>
                <td>{{ advisor.user.is_administrator }}</td>
                <td><a href="{% url 'practises:edit-advisor-roles' pk=advisor.user.id %}">edit roles</a></td>

            </tr>
        </tbody>
        {% endfor %}
    </table>
    {% else %}
    <p>No Advisors to Display</p>
</div>
  {% endif %}
{% endblock %}
{% endblock %}

src/practises/templates/practises/advisor_search.html
{% extends "base.html" %}
{% load i18n %}

{% load crispy_forms_tags %}

{% block content %}
{% block container %}

    <div class="container">
        <div id="messages" class="hidden" >
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <div id="messages_content"></div>
        </div>
        <h1>Advisor Search</h1>
    <form method="get">
        {% csrf_token %}
        {{ filter.form|crispy }}
        <button type="submit" class="btn btn-primary" name="search">Search</button>
    </form>
    </div>
    <div class="container">
        <h3>Recently signed up advisors:</h3>
        <table class="table table-striped">
            <thead>
                <tr>
                    <th scope="col">Name</th>
                    <th scope="col">Surname</th>
                    <th scope="col">Email</th>
                    <th scope="col"></th>
                </tr>
            </thead>
            {% for advisor in filter.qs %}
            <tbody>
                <tr scope="row">
                    <td>{{ advisor.surnames }}</td>
                    <td>{{ advisor.names }}</td>
                    <td>{{ advisor.advisor_contact_fk.email_address }}</td>
                    <td><button class="btn btn-success" data-advisor="{{ advisor.user.id }}" data-admin="{{ user.id }}"  onclick="sendInvite(this)" role="button">Invite</button></td>
                </tr>
            </tbody>
            {% endfor %}
        </table>
    </div>
{% endblock %}
{% endblock %}

{% block scripts %}
  <script>
        function sendInvite(e){
            var advisorId = e.getAttribute('data-advisor');
            var adminId = e.getAttribute('data-admin');
            $('#ayama-modal').modal('show');
            $.ajax({
            type: 'POST',
            headers:{
            "X-CSRFToken": '{{ csrf_token }}'
            },
            url: "{% url 'practises:invite-advisor'%}",
            data: {'advisor_id':advisorId, 'admin_id':adminId},
            success: function (response) {
                e.disabled = "disabled";
                $(e).removeClass("btn-success").addClass("btn-secondary");
                $('#messages').removeClass('hidden').addClass('alert alert-success ');
                $('#messages_content').html('Email sent to advisor');
                $('#ayama-modal').modal('hide');
            },
            error: function (response) {
                $('#ayama-modal').modal('hide')
                $('#messages').removeClass('hidden').addClass('alert alert-danger ');
                $('#messages_content').html('An error occured. Please contact an administrator.');
            }
        });
        }

</script>
{% endblock %}

src/practises/templates/practises/advisors_list.html
{% load i18n %}

{% block content %}
{% block container %}
{% if advisors %}
<div class="table_detail_rows">
    <table class="table sortable-table">
        <thead>
            <tr>
                <th scope="col" class="sort_list_alphabetically">Name</th>
                <th scope="col" class="sort_list_alphabetically">Email</th>
                <th scope="col" class="sort_list_alphabetically">Location</th>
                <th scope="col" class="numeric-sort">Employment Date</th>
                <th scope="col" class="numeric-sort">Clients</th>
            </tr>
        </thead>
        {% for advisor in advisors  %}
            <tr scope="row">
                <td><a href="{% url 'practises:advisor-summary' pk=advisor.user_id %}">{{ advisor.names }} {{ advisor.surnames }}</a>
                </td>
                <td><a href="{% url 'practises:advisor-summary' pk=advisor.user_id %}">{{ advisor.advisor_contact_fk.email_address }}</a>
                </td>
                <td><a href="{% url 'practises:advisor-summary' pk=advisor.user_id %}">{{ advisor.advisor_contact_fk.residential_city}}</a>
                </td>
                <td><a href="{% url 'practises:advisor-summary' pk=advisor.user_id %}">{{ advisor.advisor_employment_fk.employment_date }}</a>
                </td>
                <td><a href="{% url 'practises:edit-advisor-roles' pk=advisor.user.id %}">{{advisor.clients.count}}</a>
                </td>
            </tr>
        {% endfor %}
    </table>
</div>
{% else %}
<p>No Advisors to Display</p>

{% endif %}
{% endblock %}
{% endblock %}

src/practises/templates/practises/edit_advisor_detail.html
{% extends "base.html" %}
{% load i18n %}

{% block head %}
{% load crispy_forms_tags %}
{% endblock %}

{% block content %}
{% block container %}
    <div class="container">
        <h3>Edit Details</h3>
        <form action="" method="POST">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" name="submit" class="btn btn-primary">Save Changes</button>
        <button type="submit" name="cancel" class="btn btn-secondary">Cancel</button>
        </form>
    </div>
{% endblock %}
{% endblock %}

src/practises/templates/practises/edit_practise_detail.html
{% extends "base.html" %}
{% load i18n %}

{% block head %}
{% load crispy_forms_tags %}
{% endblock %}

{% block content %}
{% block container %}
    <div class="container">
        <h3>Edit Practise</h3>
        <form action="" method="POST">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" name="submit" class="btn btn-primary">Save Changes</button>
        <button type="submit" name="cancel" class="btn btn-secondary">Cancel</button>
        </form>
    </div>
{% endblock %}
{% endblock %}

src/practises/templates/practises/product_list.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}
{% block container %}
<div class="container">
  <h1>Product List</h1>
    {% if products %}
    <table class="table">
        <thead>
            <tr>
                <th scope="col">Name</th>
                <th scope="col">Type</th>
                <th scope="col">Company</th>
                <th scope="col">Is Active</th>
            </tr>
        </thead>
        {% for product in products %}
        <tbody>
            <tr scope="row">
                <td><a a href="{% url 'practises:edit-product' pk=product.id %}">{{ product.product_name }}</a></td>
                <td>{{ product.product_type }}</td>
                <td>{{ product.product_company }}</td>
                <td>{{ product.is_active|yesno:"Yes,No"}}</td>
            </tr>
        </tbody>
        {% endfor %}
    </table>
    {% else %}
    <p>No products to Display</p>
</div>
  {% endif %}
{% endblock %}
{% endblock %}