src/ayama/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path, re_path

import accounts.urls
import clients.urls
import practises.urls
import profiles.urls
import calculator.urls

from . import views

# Personalized admin site settings like title and header
admin.site.site_title = "Ayama Site Admin"
admin.site.site_header = "Ayama Administration"

urlpatterns = [
    re_path(r"^healthz/", views.healthz, name="healthz"),
    path("", views.HomePage.as_view(), name="home"),
    path("about/", views.AboutPage.as_view(), name="about"),
    path("users/", include(profiles.urls)),
    path("admin/", admin.site.urls),
    path("", include(accounts.urls)),
    path("", include(practises.urls)),
    path("", include(clients.urls)),
    path("calcs/", include(calculator.urls)),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [path("__debug__/", include(debug_toolbar.urls))]

    # Dev ref for profile pics -- should probably redo this at some point
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/calculator/urls.py
from django.urls import path

from . import views

app_name = "calculator"
urlpatterns = [
    path("main/", views.ShowCalcs.as_view(), name="show-calculator"),
]

src/clients/urls.py
from django.urls import path

from .forms import (
    AddClientContactDetailForm,
    AddClientDependentDetailsForm,
    AddClientDetailForm,
    AddClientEmploymentDetailForm,
    AddClientNoteForm,
    AddClientProductsForm,
    AddClientRatesAndReturnForm,
)
from .views import (
    AddClientDependentView,
    AddClientNoteView,
    AdvisorClientsView,
    ClientlistView,
    ClientNoteListView,
    ClientSummaryView,
    ClientWizard,
    EditClientCommunicationFrequencyView,
    EditClientContactView,
    EditClientDependentView,
    EditClientDetailsView,
    EditClientEmploymentView,
    EditClientNoteView,
    EditClientRatesView,
    UpdateClientCommunicationHistoryView,
    UpdateLastSeen,
)

app_name = "clients"
urlpatterns = [
    path(
        "clients/",
        ClientWizard.as_view(
            [
                AddClientDetailForm,
                AddClientContactDetailForm,
                AddClientEmploymentDetailForm,
                AddClientRatesAndReturnForm,
                AddClientProductsForm,
            ]
        ),
        name="add-client",
    ),
    path(
        "add_client_dependents/",
        AddClientDependentView.as_view(),
        name="add-client-dependents",
    ),
    path("clients_list/", ClientlistView.as_view(), name="clients-list"),
    path("advisor_clients/", AdvisorClientsView.as_view(), name="advisor-clients"),
    path("client_summary/<pk>/", ClientSummaryView.as_view(), name="client-summary"),
    path(
        "edit_client/<pk>/", EditClientDetailsView.as_view(), name="edit-client-details"
    ),
    path(
        "edit_client_contact/<pk>/",
        EditClientContactView.as_view(),
        name="edit-client-contact",
    ),
    path("update_comms", UpdateLastSeen.as_view(), name="update-comms",),
    path(
        "edit_client_employment/<pk>/",
        EditClientEmploymentView.as_view(),
        name="edit-client-employment",
    ),
    path(
        "edit_client_rates/<pk>/",
        EditClientRatesView.as_view(),
        name="edit-client-rates",
    ),
    path(
        "edit_client_dependent/<pk>/",
        EditClientDependentView.as_view(),
        name="edit-client-dependent",
    ),
    path(
        "edit_client_communication_frequency/<pk>/",
        EditClientCommunicationFrequencyView.as_view(),
        name="edit-client-communication-frequency",
    ),
    path("add_client_note/", AddClientNoteView.as_view(), name="add-client-note",),
    path(
        "edit_client_note/<pk>/", EditClientNoteView.as_view(), name="edit-client-note",
    ),
    path(
        "client_note_list/<pk>/", ClientNoteListView.as_view(), name="client-note-list",
    ),
    path(
        "client_comms_hist/<pk>/",
        UpdateClientCommunicationHistoryView.as_view(),
        name="edit-client-comms",
    ),
]

src/practises/views/advisor.py
from __future__ import unicode_literals

import logging

from django import forms
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.core.mail import send_mail
from django.db import transaction
from django.db.models.query_utils import Q
from django.forms.models import construct_instance
from django.http import JsonResponse
from django.http.response import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse_lazy
from django.views import generic
from formtools.wizard.views import SessionWizardView

from ..filters import AdvisorFilter
from ..forms import (
    AddAdvisorContactDetailForm,
    AddAdvisorDetailForm,
    AddAdvisorEmploymentForm,
    AddAdvisorProductsForm,
)
from ..models import (
    AdministratorDetail,
    AdvisorContactDetail,
    AdvisorDetail,
    AdvisorEmploymentDetail,
    AdvisorReminderConfig,
    PractiseDetail,
    ProductAdvisor,
    User,
)

FORMS = [
    ("0", AddAdvisorDetailForm),
    ("1", AddAdvisorContactDetailForm),
    ("2", AddAdvisorEmploymentForm),
    ("3", AddAdvisorProductsForm),
]

TEMPLATES = {
    "0": "practises/add_advisor_detail.html",
    "1": "practises/add_advisor_contact_detail.html",
    "2": "practises/add_advisor_employment_detail.html",
    "3": "practises/add_advisor_products.html",
}

log = logging.getLogger(__name__)


class AddAdvisorWizard(LoginRequiredMixin, UserPassesTestMixin, SessionWizardView):
    def test_func(self):
        return self.request.user.is_administrator or self.request.user.is_superuser

    def get_template_names(self):
        return TEMPLATES[self.steps.current]

    def dispatch(self, request, *args, **kwargs):
        self.practise = kwargs.get("practise", None)
        return super(AddAdvisorWizard, self).dispatch(request, *args, **kwargs)

    def get_form(self, step=None, data=None, files=None):
        form = super().get_form(step, data, files)
        if self.steps.current == "0" and step is None:
            if self.request.user.is_superuser:
                form.fields["practise_id_fk"].queryset = PractiseDetail.objects.all()
            elif self.request.user.is_administrator and self.request.user.is_advisor:
                practise_id = self.request.user.Advisor.practise_id_fk.id
                form.fields["practise_id_fk"].queryset = PractiseDetail.objects.filter(
                    id=practise_id
                ).all()
            elif self.request.user.is_administrator:
                practise_id = self.request.user.Administrator.practise_id_fk.id
                form.fields["practise_id_fk"].queryset = PractiseDetail.objects.filter(
                    id=practise_id
                ).all()

        return form

    def get_form_initial(self, step):
        self.initial_dict.get(self.steps.current, {})
        if self.steps.current == "0" and self.practise is not None:
            return self.initial_dict.get(step, {"practise_id_fk": self.practise})
        elif self.request.user.is_administrator and self.request.user.is_advisor:
            self.practise = self.request.user.Advisor.practise_id_fk
            return self.initial_dict.get(step, {"practise_id_fk": self.practise})
        elif self.request.user.is_administrator:
            self.practise = self.request.user.Administrator.practise_id_fk
            return self.initial_dict.get(step, {"practise_id_fk": self.practise})

    def get_context_data(self, form, **kwargs):
        context = super(AddAdvisorWizard, self).get_context_data(form=form, **kwargs)
        if self.steps.current != "0":
            advisor_name = []
            step0data = self.get_cleaned_data_for_step("0")
            advisor_name.append(step0data["title"].capitalize())
            advisor_name.append(step0data["initials"].capitalize())
            advisor_name.append(step0data["surnames"].capitalize())
            context.update({"advisor_name": " ".join(advisor_name)})
        return context

    @transaction.atomic
    def done(self, form_list, form_dict, **kwargs):
        try:
            User = get_user_model()
            # models backing db
            advisor = AdvisorDetail()
            advisorContact = AdvisorContactDetail()
            advisorEmployment = AdvisorEmploymentDetail()
            advisorCommsConfig = AdvisorReminderConfig()
            productAdvisor = ProductAdvisor()
            # form instances
            form_data = [form.cleaned_data for form in form_list]

            advisor = construct_instance(
                form_dict["0"],
                advisor,
                form_dict["0"]._meta.fields,
                form_dict["0"]._meta.exclude,
            )

            advisorContact = construct_instance(
                form_dict["1"],
                advisorContact,
                form_dict["1"]._meta.fields,
                form_dict["1"]._meta.exclude,
            )

            advisorEmployment = construct_instance(
                form_dict["2"],
                advisorEmployment,
                form_dict["2"]._meta.fields,
                form_dict["2"]._meta.exclude,
            )

            productAdvisor = construct_instance(
                form_dict["3"],
                productAdvisor,
                form_dict["3"]._meta.fields,
                form_dict["3"]._meta.exclude,
            )

            existing_user = User.objects.filter(
                Q(email=advisorContact.email_address)
                | Q(username=advisorContact.email_address)
            )

            if not existing_user:
                user = User.objects.create_user(
                    email=advisorContact.email_address,
                    username=advisorContact.email_address,
                    password="password",
                    first_name=advisor.names,
                    last_name=advisor.surnames,
                    name=advisor.names + " " + advisor.surnames,
                )  # default password for now, to revise
                user.is_advisor = True
                user.is_administrator = False
                user.is_staff = True
                user.is_superuser = False
                user.save()
                advisor.user = user

                advisorContact.modified_by = self.request.user
                advisorContact.save()
                advisor.advisor_contact_fk = advisorContact

                advisorEmployment.modified_by = self.request.user
                advisorEmployment.save()
                advisor.advisor_employment_fk = advisorEmployment

                productAdvisor.modified_by = self.request.user
                productAdvisor.advisor_id_fk = advisor
                productAdvisor.save()

                productAdvisor.product_id_fk.set(form_data[3]["product_id_fk"])
                productAdvisor.save()

                advisorCommsConfig.modified_by = self.request.user
                advisorCommsConfig.save()

                advisor.reminder_config_freq_fk = advisorCommsConfig
                advisor.modified_by = self.request.user

                advisor.save()

                messages.add_message(
                    self.request, messages.SUCCESS, "advisor successfully added."
                )
            else:
                messages.add_message(
                    self.request, messages.ERROR, "Email address already in use."
                )
                return HttpResponseRedirect(self.request.path_info)
        except Exception as e:
            log.info(e)
            messages.add_message(self.request, messages.ERROR, e)
            return HttpResponseRedirect(reverse_lazy("home"))

        return HttpResponseRedirect(reverse_lazy("home"))


class AdvisorlistView(LoginRequiredMixin, UserPassesTestMixin, generic.ListView):
    template_name = "practises/advisor_list.html"
    model = AdvisorDetail

    def test_func(self):
        return self.request.user.is_administrator or self.request.user.is_superuser

    def get_context_data(self, **kwargs):
        context = super(AdvisorlistView, self).get_context_data(**kwargs)
        user = self.request.user

        if user.is_administrator and user.is_advisor:
            advisors = AdvisorDetail.objects.filter(
                practise_id_fk=user.Advisor.practise_id_fk
            ).select_related("advisor_contact_fk")
            context = {"advisors": advisors}
        elif user.is_administrator:
            advisors = AdvisorDetail.objects.filter(
                practise_id_fk=user.Administrator.practise_id_fk
            ).select_related("advisor_contact_fk")
            context = {"advisors": advisors}
        elif user.is_superuser:
            advisors = AdvisorDetail.objects.all().select_related("advisor_contact_fk")
            context = {"advisors": advisors}

        return context


class AdvisorSummaryView(LoginRequiredMixin, UserPassesTestMixin, generic.DetailView):
    template_name = "practises/advisor_summary.html"
    model = AdvisorDetail

    def test_func(self):
        return self.request.user.is_administrator or self.request.user.is_superuser

    def get_context_data(self, **kwargs):
        context = super(AdvisorSummaryView, self).get_context_data(**kwargs)
        advisor_id = self.kwargs["pk"]
        advisor = AdvisorDetail.objects.get(user=advisor_id)
        products = ProductAdvisor.objects.get(advisor_id_fk=advisor_id)
        context = {"advisor": advisor, "products": products.product_id_fk.all()}
        return context


class EditAdvisorDetailView(
    LoginRequiredMixin, UserPassesTestMixin, generic.UpdateView
):
    template_name = "practises/edit_advisor_detail.html"
    model = AdvisorDetail
    fields = (
        "title",
        "initials",
        "surnames",
        "names",
        "known_as",
        "sa_id",
        "passport_no",
        "position",
        "employment_date",
        "personnel_number",

src/templates/advisors/home.html
{% load thumbnail %}

{% comment %} ++++++++++++ LEFT/PROFILE INFO START +++++++++++ {% endcomment %}

<div class="container" style="margin-top: 20px;">
    <div class="row">
        <div class="col-xl-3 left-dash-column">
            <div class="sidebar">
                <div class="card card-container">
                    <img class="card-img-top profile-img"
                        src="{% thumbnail user.profile.picture|default:'advisor.png' 150x150 crop %}"
                        alt="Card image cap">
                    <div class="align-center">
                        <h4 class="figly-h4"> {{ user.get_full_name}}</h4>
                        <p class="figly-p">{{ user.residential_address_line_1}}{{user.Advisor.practise_id_fk}}</p>
                        {% comment %} <p>{{user.number}}</p> {% endcomment %}
                    </div>
                    <hr/>
                    <p class="figly-p">
                        <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-telephone-fill figly-icon"
                            fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                            <path fill-rule="evenodd"
                                d="M2.267.98a1.636 1.636 0 0 1 2.448.152l1.681 2.162c.309.396.418.913.296 1.4l-.513 2.053a.636.636 0 0 0 .167.604L8.65 9.654a.636.636 0 0 0 .604.167l2.052-.513a1.636 1.636 0 0 1 1.401.296l2.162 1.681c.777.604.849 1.753.153 2.448l-.97.97c-.693.693-1.73.998-2.697.658a17.47 17.47 0 0 1-6.571-4.144A17.47 17.47 0 0 1 .639 4.646c-.34-.967-.035-2.004.658-2.698l.97-.969z" />
                        </svg>
                        <a href="#" class="user-dash-link">{{user.Advisor.advisor_contact_fk.cellphone_number}}</a>
                    </p>
                    <p class="figly-p">
                        <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-envelope-fill figly-icon"
                            fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                            <path fill-rule="evenodd"
                                d="M.05 3.555A2 2 0 0 1 2 2h12a2 2 0 0 1 1.95 1.555L8 8.414.05 3.555zM0 4.697v7.104l5.803-3.558L0 4.697zM6.761 8.83l-6.57 4.027A2 2 0 0 0 2 14h12a2 2 0 0 0 1.808-1.144l-6.57-4.027L8 9.586l-1.239-.757zm3.436-.586L16 11.801V4.697l-5.803 3.546z" />
                        </svg>
                        <a href="#" class="user-dash-link">{{user.email}}
                        </a>
                    </p>
                    <hr />
                </div>
                <div class="card  card-container dropdown-button-container">

                    {% comment %} +++++++++ MANAGE CLIENTS DROPDOWN ++++++++ {% endcomment %}

                    <div>
                        <button class="figly-h5 dash-dropdown-btn" type="button" data-toggle="collapse"
                            data-target="#multiCollapseExample1" aria-expanded="false"
                            aria-controls="multiCollapseExample1">MANAGE CLIENTS</button>
                        <div class="col">
                            <div class="collapse multi-collapse" id="multiCollapseExample1">
                                <div>
                                    <p class="dropdown-options">
                                        <a href=" {% url 'clients:add-client' %} " class="user-dash-link">
                                            Add Client
                                        </a>
                                    </p>
                                </div>
                                <div>
                                    <p class="dropdown-options">
                                        <a href="{% url 'clients:add-client-dependents' %}" class="user-dash-link">
                                            Add Client Dependants</a>
                                    </p>
                                </div>
                            </div>
                        </div>
                    </div>

                    {% comment %} +++++++++ MANAGE ADVISORS DROPDOWN ++++++++ {% endcomment %}

                    <div>
                        <button class="figly-h5 dash-dropdown-btn" type="button" data-toggle="collapse"
                            data-target="#multiCollapseExample2" aria-expanded="false"
                            aria-controls="multiCollapseExample2">CALCULATORS</button>
                        <div class="col">
                            <div class="collapse multi-collapse" id="multiCollapseExample2">
                                <div>
                                    <p class="dropdown-options">
                                        <a href="{% url 'calculator:show-calculator' %}" class="user-dash-link">
                                            Future value calculator</a>
                                    </p>
                                </div>
                            </div>
                        </div>
                    </div>                  
                </div>
            </div>
        </div>

        {% comment %} ++++++++++++ LEFT/PROFILE INFO END +++++++++++ {% endcomment %}

        <div class="col-xl-9 right-dash-column">
                        
                {% load  client_scheduler %}
                {% client_scheduler user=user %}        

            <div class="card-container dashboard_list_details">
                <div class="row">
                    <div class="col-xl-8">
                        <div class="figly-h4">
                            Clients List
                        </div>
                    </div>
                </div>

                {% load  advisor_clients %}
                {% advisor_clients user=user %}

            </div>
        </div>
    </div>
</div>