src/ayama/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path, re_path

import accounts.urls
import clients.urls
import practises.urls
import profiles.urls
import calculator.urls

from . import views

# Personalized admin site settings like title and header
admin.site.site_title = "Ayama Site Admin"
admin.site.site_header = "Ayama Administration"

urlpatterns = [
    re_path(r"^healthz/", views.healthz, name="healthz"),
    path("", views.HomePage.as_view(), name="home"),
    path("about/", views.AboutPage.as_view(), name="about"),
    path("users/", include(profiles.urls)),
    path("admin/", admin.site.urls),
    path("", include(accounts.urls)),
    path("", include(practises.urls)),
    path("", include(clients.urls)),
    path("calcs/", include(calculator.urls)),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [path("__debug__/", include(debug_toolbar.urls))]

    # Dev ref for profile pics -- should probably redo this at some point
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/clients/urls.py
from django.urls import path

from .forms import (
    AddClientContactDetailForm,
    AddClientDependentDetailsForm,
    AddClientDetailForm,
    AddClientEmploymentDetailForm,
    AddClientNoteForm,
    AddClientProductsForm,
    AddClientRatesAndReturnForm,
)
from .views import (
    AddClientDependentView,
    AddClientNoteView,
    AdvisorClientsView,
    ClientlistView,
    ClientNoteListView,
    ClientSummaryView,
    ClientWizard,
    EditClientCommunicationFrequencyView,
    EditClientContactView,
    EditClientDependentView,
    EditClientDetailsView,
    EditClientEmploymentView,
    EditClientNoteView,
    EditClientRatesView,
    UpdateClientCommunicationHistoryView,
    UpdateLastSeen,
)

app_name = "clients"
urlpatterns = [
    path(
        "clients/",
        ClientWizard.as_view(
            [
                AddClientDetailForm,
                AddClientContactDetailForm,
                AddClientEmploymentDetailForm,
                AddClientRatesAndReturnForm,
                AddClientProductsForm,
            ]
        ),
        name="add-client",
    ),
    path(
        "add_client_dependents/",
        AddClientDependentView.as_view(),
        name="add-client-dependents",
    ),
    path("clients_list/", ClientlistView.as_view(), name="clients-list"),
    path("advisor_clients/", AdvisorClientsView.as_view(), name="advisor-clients"),
    path("client_summary/<pk>/", ClientSummaryView.as_view(), name="client-summary"),
    path(
        "edit_client/<pk>/", EditClientDetailsView.as_view(), name="edit-client-details"
    ),
    path(
        "edit_client_contact/<pk>/",
        EditClientContactView.as_view(),
        name="edit-client-contact",
    ),
    path("update_comms", UpdateLastSeen.as_view(), name="update-comms",),
    path(
        "edit_client_employment/<pk>/",
        EditClientEmploymentView.as_view(),
        name="edit-client-employment",
    ),
    path(
        "edit_client_rates/<pk>/",
        EditClientRatesView.as_view(),
        name="edit-client-rates",
    ),
    path(
        "edit_client_dependent/<pk>/",
        EditClientDependentView.as_view(),
        name="edit-client-dependent",
    ),
    path(
        "edit_client_communication_frequency/<pk>/",
        EditClientCommunicationFrequencyView.as_view(),
        name="edit-client-communication-frequency",
    ),
    path("add_client_note/", AddClientNoteView.as_view(), name="add-client-note",),
    path(
        "edit_client_note/<pk>/", EditClientNoteView.as_view(), name="edit-client-note",
    ),
    path(
        "client_note_list/<pk>/", ClientNoteListView.as_view(), name="client-note-list",
    ),
    path(
        "client_comms_hist/<pk>/",
        UpdateClientCommunicationHistoryView.as_view(),
        name="edit-client-comms",
    ),
]

src/practises/urls.py
from django.urls import path, re_path

from .forms import (
    AddAdministratorContactDetailForm,
    AddAdministratorDetailForm,
    AddAdvisorContactDetailForm,
    AddAdvisorDetailForm,
    AddAdvisorEmploymentForm,
    AddAdvisorProductsForm,
    AddPractiseDetailForm,
    SignUpAdministratorDetailForm,
    SignUpAdvisorDetailForm,
)
from .views import (
    AddAdministratorWizard,
    AddAdvisorWizard,
    AddClientProductView,
    AddPractiseView,
    AddProductView,
    AdministratorlistView,
    AdministratorSummaryView,
    AdvisorlistView,
    AdvisorSearch,
    AdvisorSummaryView,
    EditAdministratorContactView,
    EditAdministratorDetailView,
    EditAdvisorContactView,
    EditAdvisorDetailView,
    EditPractiseView,
    EditProductView,
    EditReminderPreferencesView,
    EditRolesView,
    InviteAdvisor,
    LinkAdvisor,
    ProductlistView,
    SignUpAdministratorWizard,
    SignUpAdvisorWizard,
    ViewClientProductView,
)

app_name = "practises"
urlpatterns = [
    path("add_practise/", AddPractiseView.as_view(), name="add-practise"),
    path("edit_practise/<pk>/", EditPractiseView.as_view(), name="edit-practise"),
    path(
        "advisor/",
        AddAdvisorWizard.as_view(
            [
                AddAdvisorDetailForm,
                AddAdvisorContactDetailForm,
                AddAdvisorEmploymentForm,
                AddAdvisorProductsForm,
            ]
        ),
        name="add-advisor",
    ),
    path(
        "advisor/<int:practise>/",
        AddAdvisorWizard.as_view([AddAdvisorDetailForm, AddAdvisorContactDetailForm]),
        name="add-advisor",
    ),
    path(
        "administrator/",
        AddAdministratorWizard.as_view(
            [AddAdministratorDetailForm, AddAdministratorContactDetailForm]
        ),
        name="add-administrator",
    ),
    path(
        "admin_sign_up/",
        SignUpAdministratorWizard.as_view(
            [
                SignUpAdministratorDetailForm,
                AddAdministratorContactDetailForm,
                AddPractiseDetailForm,
            ]
        ),
        name="sign-up-administrator",
    ),
    path(
        "advisor_sign_up/",
        SignUpAdvisorWizard.as_view(
            [SignUpAdministratorDetailForm, AddAdvisorContactDetailForm]
        ),
        name="sign-up-advisor",
    ),
    path("advisor_list/", AdvisorlistView.as_view(), name="advisor-list"),
    path("advisor_summary/<pk>/", AdvisorSummaryView.as_view(), name="advisor-summary"),
    path(
        "edit_advisor_detail/<pk>/",
        EditAdvisorDetailView.as_view(),
        name="edit-advisor-detail",
    ),
    path(
        "edit_advisor_contact/<pk>/",
        EditAdvisorContactView.as_view(),
        name="edit-advisor-contact",
    ),
    path(
        "administrator_list/",
        AdministratorlistView.as_view(),
        name="administrator-list",
    ),
    path(
        "administrator_summary/<pk>/",
        AdministratorSummaryView.as_view(),
        name="administrator-summary",
    ),
    path(
        "edit_administrator_detail/<pk>/",
        EditAdministratorDetailView.as_view(),
        name="edit-administrator-detail",
    ),
    path(
        "edit_administrator_contact/<pk>/",
        EditAdministratorContactView.as_view(),
        name="edit-administrator-contact",
    ),
    path(
        "edit_advisor_reminder/<pk>/",
        EditReminderPreferencesView.as_view(),
        name="edit-advisor-reminder-config",
    ),
    re_path(r"^search/$", AdvisorSearch, name="advisor-search"),
    path(
        "invite_advisor",
        InviteAdvisor.as_view(),
        name="invite-advisor",
    ),
    path(
        "link_advisor",
        LinkAdvisor.as_view(),
        name="link-advisor",
    ),
    path(
        "edit_advisor_roles/<pk>/",
        EditRolesView.as_view(),
        name="edit-advisor-roles",
    ),
    path("add_product/", AddProductView.as_view(), name="add-product"),
    path("product_list/", ProductlistView.as_view(), name="list-products"),
    path("edit_product/<pk>/", EditProductView.as_view(), name="edit-product"),
    path(
        "view_client_product/<int:client_id>",
        ViewClientProductView.as_view(),
        name="view-client-product",
    ),
    path(
        "add_client_product/",
        AddClientProductView,
        name="add-client-product",
    ),
]

src/templates/administration/home.html
{% load thumbnail %}

{% comment %} ++++++++++++ LEFT/PROFILE INFO START +++++++++++ {% endcomment %}

<div class="container" style="margin-top: 20px;">
    <div class="row">
        <div class="col-xl-3 left-dash-column">
            <div class="sidebar">
                <div class="card card-container">
                    <img class="card-img-top profile-img"
                        src="{% thumbnail user.profile.picture|default:'example_photo.jpg' 150x150 crop %}"
                        alt="Card image cap">
                    <div class="align-center">
                        <h4 class="figly-h4">{{ user.name}}</h4>
                        <p class="figly-p">{{user.Administrator.practise_id_fk}}</p>
                    </div>
                    <hr/>
                    <p class="figly-p">
                        <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-telephone-fill figly-icon"
                            fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                            <path fill-rule="evenodd"
                                d="M2.267.98a1.636 1.636 0 0 1 2.448.152l1.681 2.162c.309.396.418.913.296 1.4l-.513 2.053a.636.636 0 0 0 .167.604L8.65 9.654a.636.636 0 0 0 .604.167l2.052-.513a1.636 1.636 0 0 1 1.401.296l2.162 1.681c.777.604.849 1.753.153 2.448l-.97.97c-.693.693-1.73.998-2.697.658a17.47 17.47 0 0 1-6.571-4.144A17.47 17.47 0 0 1 .639 4.646c-.34-.967-.035-2.004.658-2.698l.97-.969z" />
                        </svg>
                        <a href="#" class="user-dash-link">(012) 345 6789</a>
                    </p>
                    <p class="figly-p">
                        <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-envelope-fill figly-icon"
                            fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                            <path fill-rule="evenodd"
                                d="M.05 3.555A2 2 0 0 1 2 2h12a2 2 0 0 1 1.95 1.555L8 8.414.05 3.555zM0 4.697v7.104l5.803-3.558L0 4.697zM6.761 8.83l-6.57 4.027A2 2 0 0 0 2 14h12a2 2 0 0 0 1.808-1.144l-6.57-4.027L8 9.586l-1.239-.757zm3.436-.586L16 11.801V4.697l-5.803 3.546z" />
                        </svg>
                        <a href="#" class="user-dash-link"> example@email.com
                        </a>
                    </p>
                    <hr/>
                </div>
                <div class="card  card-container dropdown-button-container">

                    {% comment %} +++++++++ MANAGE CLIENTS DROPDOWN ++++++++ {% endcomment %}

                    <div>
                        <button class="figly-h4 dash-dropdown-btn" type="button" data-toggle="collapse"
                            data-target="#multiCollapseExample1" aria-expanded="false"
                            aria-controls="multiCollapseExample1">Manage Clients</button>

                        <div class="col">
                            <div class="collapse multi-collapse" id="multiCollapseExample1">
                                <div>
                                    <p class="dropdown-options">
                                        <a href=" {% url 'clients:add-client' %} " class="user-dash-link">
                                            Add Client</a>
                                    </p>
                                </div>
                                <div>
                                    <p class="dropdown-options">
                                        <a href=" {% url 'clients:add-client-dependents' %}" class="user-dash-link">
                                            Add Client Dependants</a>
                                    </p>
                                </div>
                            </div>
                        </div>
                    </div>

                    {% comment %} +++++++++ MANAGE ADVISORS DROPDOWN ++++++++ {% endcomment %}

                    <div>
                        <button class="figly-h4 dash-dropdown-btn" type="button" data-toggle="collapse"
                            data-target="#multiCollapseExample2" aria-expanded="false"
                            aria-controls="multiCollapseExample2">Manage Advisors</button>

                        <div class="col">
                            <div class="collapse multi-collapse" id="multiCollapseExample2">
                                <div>
                                    <p class="dropdown-options">
                                        <a href="{% url 'practises:add-advisor' %}" class="user-dash-link">
                                            Add Advisor</a>
                                    </p>
                                </div>
                            </div>
                        </div>
                    </div>

                    {% comment %} +++++++++ MANAGE PRACTISE DROPDOWN ++++++++ {% endcomment %}

                    <div>
                        <button class="figly-h4 dash-dropdown-btn" type="button" data-toggle="collapse"
                            data-target="#multiCollapseExample3" aria-expanded="false"
                            aria-controls="multiCollapseExample3">Manage Practise</button>

                        <div class="col">
                            <div class="collapse multi-collapse" id="multiCollapseExample3">
                                <div>
                                    <p class="dropdown-options">
                                        <a href="{% url 'practises:sign-up-advisor' %}" class="user-dash-link">
                                            Add Advisor</a>
                                    </p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        {% comment %} ++++++++++++ LEFT/PROFILE INFO END +++++++++++ {% endcomment %}

        <div class="col-xl-9 right-dash-column">

            <div class=" card-container dashboard_list_details" style="margin-top: 30px;">
                <div class="row">
                        <div class="col-xl-8">
                            <div class="figly-h4">
                                Advisors List
                            </div>
                        </div>                  
                    </div>
                    {% load advisors_list %}

                    {% advisors_list user=user %}

            </div>
            <div class="card-container dashboard_list_details">
                <div class="row">
                    <div class="col-xl-8">
                        <div class="figly-h4">
                            Clients List
                        </div>
                    </div>                  
                </div>

                {% load clients_list %}
                {% clients_list user=user %}
            </div>
        </div>        
            
    </div>
</div>